export type LegalStatus = "Legal" | "Gray" | "Illegal";

export type LegalHeatmapEntry = {
  id: string;
  country: string;
  region: string;
  latitude: number;
  longitude: number;
  status: LegalStatus;
  summary: string;
  sourceLabel: string;
  sourceUrl: string;
  reviewedOn: string;
};

export const LEGAL_HEATMAP_DATA: LegalHeatmapEntry[] = [
  {
    id: "us-ca",
    country: "United States",
    region: "California",
    latitude: 36.7783,
    longitude: -119.4179,
    status: "Gray",
    summary: "Enforcement and local ordinances vary by county/city and specific venues.",
    sourceLabel: "Wikipedia: Public nudity in the United States",
    sourceUrl: "https://en.wikipedia.org/wiki/Public_nudity#United_States",
    reviewedOn: "2026-03-31",
  },
  {
    id: "us-fl",
    country: "United States",
    region: "Florida",
    latitude: 27.6648,
    longitude: -81.5158,
    status: "Illegal",
    summary: "Public nudity is generally prohibited outside explicitly authorized places.",
    sourceLabel: "Wikipedia: Public nudity in the United States",
    sourceUrl: "https://en.wikipedia.org/wiki/Public_nudity#United_States",
    reviewedOn: "2026-03-31",
  },
  {
    id: "us-vt",
    country: "United States",
    region: "Vermont",
    latitude: 44.5588,
    longitude: -72.5778,
    status: "Gray",
    summary: "Some allowances exist but local regulations and conduct laws still apply.",
    sourceLabel: "Wikipedia: Public nudity in the United States",
    sourceUrl: "https://en.wikipedia.org/wiki/Public_nudity#United_States",
    reviewedOn: "2026-03-31",
  },
  {
    id: "es-cat",
    country: "Spain",
    region: "Catalonia",
    latitude: 41.8205,
    longitude: 1.8677,
    status: "Legal",
    summary: "Public nudity is broadly legal; local signage and municipal guidance still matter.",
    sourceLabel: "Wikipedia: Public nudity in Spain",
    sourceUrl: "https://en.wikipedia.org/wiki/Public_nudity#Spain",
    reviewedOn: "2026-03-31",
  },
  {
    id: "es-and",
    country: "Spain",
    region: "Andalusia",
    latitude: 37.5443,
    longitude: -4.7278,
    status: "Legal",
    summary: "Many coastal areas are permissive, especially where naturism is established.",
    sourceLabel: "Wikipedia: Public nudity in Spain",
    sourceUrl: "https://en.wikipedia.org/wiki/Public_nudity#Spain",
    reviewedOn: "2026-03-31",
  },
  {
    id: "es-md",
    country: "Spain",
    region: "Community of Madrid",
    latitude: 40.4168,
    longitude: -3.7038,
    status: "Gray",
    summary: "Legal baseline exists but urban enforcement and complaints can influence outcomes.",
    sourceLabel: "Wikipedia: Public nudity in Spain",
    sourceUrl: "https://en.wikipedia.org/wiki/Public_nudity#Spain",
    reviewedOn: "2026-03-31",
  },
  {
    id: "de-bb",
    country: "Germany",
    region: "Brandenburg",
    latitude: 52.4125,
    longitude: 12.5316,
    status: "Legal",
    summary: "FKK culture is established and often accepted in designated/open contexts.",
    sourceLabel: "Wikipedia: Public nudity in Germany",
    sourceUrl: "https://en.wikipedia.org/wiki/Public_nudity#Germany",
    reviewedOn: "2026-03-31",
  },
  {
    id: "de-by",
    country: "Germany",
    region: "Bavaria",
    latitude: 48.7904,
    longitude: 11.4979,
    status: "Gray",
    summary: "Acceptance varies by municipality and setting.",
    sourceLabel: "Wikipedia: Public nudity in Germany",
    sourceUrl: "https://en.wikipedia.org/wiki/Public_nudity#Germany",
    reviewedOn: "2026-03-31",
  },
  {
    id: "de-hh",
    country: "Germany",
    region: "Hamburg",
    latitude: 53.5511,
    longitude: 9.9937,
    status: "Gray",
    summary: "Urban areas can be less tolerant outside known naturist spaces.",
    sourceLabel: "Wikipedia: Public nudity in Germany",
    sourceUrl: "https://en.wikipedia.org/wiki/Public_nudity#Germany",
    reviewedOn: "2026-03-31",
  },
  {
    id: "fr-paca",
    country: "France",
    region: "Provence-Alpes-Côte d’Azur",
    latitude: 43.9352,
    longitude: 6.0679,
    status: "Gray",
    summary: "Generally tolerated in recognized naturist areas.",
    sourceLabel: "Wikipedia: Public nudity in France",
    sourceUrl: "https://en.wikipedia.org/wiki/Public_nudity#France",
    reviewedOn: "2026-03-31",
  },
  {
    id: "fr-occ",
    country: "France",
    region: "Occitanie",
    latitude: 43.8927,
    longitude: 3.2828,
    status: "Gray",
    summary: "Several naturist zones exist, but rules outside them are stricter.",
    sourceLabel: "Wikipedia: Public nudity in France",
    sourceUrl: "https://en.wikipedia.org/wiki/Public_nudity#France",
    reviewedOn: "2026-03-31",
  },
  {
    id: "fr-idf",
    country: "France",
    region: "Île-de-France",
    latitude: 48.8499,
    longitude: 2.637,
    status: "Illegal",
    summary: "Dense urban environments tend to have higher enforcement risk.",
    sourceLabel: "Wikipedia: Public nudity in France",
    sourceUrl: "https://en.wikipedia.org/wiki/Public_nudity#France",
    reviewedOn: "2026-03-31",
  },
  {
    id: "ca-bc",
    country: "Canada",
    region: "British Columbia",
    latitude: 53.7267,
    longitude: -127.6476,
    status: "Gray",
    summary: "Federal indecency/nudity law applies; outcomes depend on context and enforcement.",
    sourceLabel: "Canada Criminal Code §174",
    sourceUrl: "https://laws-lois.justice.gc.ca/eng/acts/C-46/section-174.html",
    reviewedOn: "2026-03-31",
  },
  {
    id: "ca-on",
    country: "Canada",
    region: "Ontario",
    latitude: 51.2538,
    longitude: -85.3232,
    status: "Gray",
    summary: "Authorities evaluate public setting and offensiveness context.",
    sourceLabel: "Canada Criminal Code §174",
    sourceUrl: "https://laws-lois.justice.gc.ca/eng/acts/C-46/section-174.html",
    reviewedOn: "2026-03-31",
  },
  {
    id: "ca-qc",
    country: "Canada",
    region: "Quebec",
    latitude: 52.9399,
    longitude: -73.5491,
    status: "Gray",
    summary: "Tolerance can vary by municipality and location type.",
    sourceLabel: "Canada Criminal Code §174",
    sourceUrl: "https://laws-lois.justice.gc.ca/eng/acts/C-46/section-174.html",
    reviewedOn: "2026-03-31",
  },
  {
    id: "mx-qr",
    country: "Mexico",
    region: "Quintana Roo",
    latitude: 19.1817,
    longitude: -88.4791,
    status: "Gray",
    summary: "Tourist destinations can be more permissive in specific zones.",
    sourceLabel: "Wikipedia: Public nudity in Mexico",
    sourceUrl: "https://en.wikipedia.org/wiki/Public_nudity#Mexico",
    reviewedOn: "2026-03-31",
  },
  {
    id: "mx-bcs",
    country: "Mexico",
    region: "Baja California Sur",
    latitude: 26.0444,
    longitude: -111.6661,
    status: "Gray",
    summary: "Local practice differs across beaches and municipalities.",
    sourceLabel: "Wikipedia: Public nudity in Mexico",
    sourceUrl: "https://en.wikipedia.org/wiki/Public_nudity#Mexico",
    reviewedOn: "2026-03-31",
  },
  {
    id: "mx-cdmx",
    country: "Mexico",
    region: "Mexico City",
    latitude: 19.4326,
    longitude: -99.1332,
    status: "Illegal",
    summary: "Urban public spaces generally have stricter enforcement risk.",
    sourceLabel: "Wikipedia: Public nudity in Mexico",
    sourceUrl: "https://en.wikipedia.org/wiki/Public_nudity#Mexico",
    reviewedOn: "2026-03-31",
  },
];