export const policyContact = {
  legalName: "BareUnity",
  domain: "BareUnity",
  email: "jeroen@bareunity.com",
} as const;

export type PolicyGroup = {
  id: string;
  eyebrow: string;
  title: string;
  body: string[];
  cards: string[];
};

export const policyGroups: PolicyGroup[] = [
  {
    id: "terms-of-service",
    eyebrow: "Terms of Service",
    title: "Membership terms, platform scope, and account responsibility",
    body: [
      "These Terms govern access to BareUnity, an adult-only naturist community for respectful, consent-first connection, discussion, member profiles, gallery sharing, messaging, venue discovery, and community features. By creating an account, signing in, submitting content, opening messages, using venue discovery, or otherwise accessing BareUnity, you agree to these Terms and every policy linked from this legal center.",
      "BareUnity may approve, decline, suspend, restrict, remove, or require re-verification of accounts when needed to protect members, comply with law, investigate abuse, prevent fraud, preserve evidence, maintain trust, enforce these policies, or protect the non-sexual naturist purpose of the community. Access is a revocable membership privilege, not a guaranteed right, property interest, employment relationship, agency relationship, or entitlement to any specific feature.",
      "Membership is personal to you. You may not sell, transfer, sublicense, lend, share, lease, automate, scrape, crawl, index, mirror, reverse engineer, benchmark for a competing product, or use BareUnity to create member lists, facial recognition datasets, marketing audiences, AI training data, surveillance tools, or competing services.",
      "You are responsible for your account activity, credentials, devices, recovery email, profile accuracy, content, legal compliance, and member interactions. If you suspect unauthorized access, contact BareUnity promptly and take reasonable steps to secure your email, device, passwords, and connected accounts.",
    ],
    cards: [
      "BareUnity is a community platform, not a hotel, resort, travel agency, payment processor, dating service, escort service, medical provider, legal adviser, emergency service, public authority, insurer, background-check provider, or guarantor of member conduct.",
      "Businesses, venues, press, researchers, bots, data brokers, law firms, investigators, and automated systems need written permission before accessing member areas or collecting platform data.",
      "Do not use BareUnity for sexual solicitation, illegal transactions, trafficking, exploitation, harassment, doxxing, fraud, scams, scraping, spam, malware, vulnerability testing, or ban evasion.",
      "Conflicting signed agreements, checkout terms, feature-specific rules, or in-product safety instructions may add to these baseline policies for the relevant feature or user.",
    ],
  },
  {
    id: "privacy-policy",
    eyebrow: "Privacy Policy",
    title: "Information we collect, use, share, protect, and retain",
    body: [
      "BareUnity collects information you provide directly, including registration details, username, display name, email address, password or authentication data, age or date-of-birth confirmation, profile information, photos, posts, comments, messages, reports, support requests, verification responses, payment or subscription identifiers, venue-listing submissions, notification settings, and account preferences.",
      "We also collect information generated by your use of the service, including session data, device and browser details, IP address, approximate location signals, security events, moderation history, friend requests, likes, notifications, uploads, feature interactions, referral or link data, crash logs, rate-limit events, and anti-abuse signals. We use this information to provide the service, verify adult access, maintain safety, personalize member experiences, prevent abuse, investigate reports, send service messages, improve reliability, measure feature performance, defend legal claims, and comply with legal obligations.",
      "BareUnity does not sell personal information as its core business model. We may share information with service providers that help run hosting, authentication, storage, email, analytics, security, moderation, support, payments, legal operations, and compliance; with authorities when legally required or necessary to prevent harm; with other members according to your profile, posting, messaging, and visibility choices; with venues or partners only where a feature clearly requires it; and with successors if BareUnity is reorganized, merged, financed, sold, or transferred.",
      "We retain information for as long as needed to provide the service, meet legal obligations, resolve disputes, enforce policies, protect safety, prevent fraud, maintain backups, and keep business records. Account deletion requests may not immediately remove information that appears in moderation records, backups, legal holds, unresolved reports, transaction records, audit logs, law-enforcement preservation, or content already shared with other members under these policies.",
    ],
    cards: [
      "Contact jeroen@bareunity.com to request access, correction, deletion, portability, objection, restriction, withdrawal of consent, or appeal of privacy decisions where those rights apply.",
      "Verification and safety data is restricted to trust, safety, fraud prevention, member support, compliance, and legal uses; do not upload more sensitive data than requested.",
      "Members should avoid posting personal addresses, phone numbers, financial information, identity documents, workplace details, travel plans, or other sensitive details in public or shared spaces.",
      "We use reasonable technical and organizational safeguards, but no online service can guarantee perfect security, uninterrupted availability, or absolute prevention of unauthorized access.",
    ],
  },
  {
    id: "privacy-rights-cookies",
    eyebrow: "Privacy Rights, Cookies & Regional Notices",
    title: "Your privacy choices and tracking controls",
    body: [
      "Depending on where you live, you may have rights to know what personal information we process, access it, correct it, delete it, receive a portable copy, restrict or object to certain processing, withdraw consent, opt out of certain sharing, limit sensitive-data use, or complain to a privacy regulator. We will honor valid rights requests where applicable law requires it and may verify your identity before acting.",
      "BareUnity may use cookies, local storage, session tokens, pixels, analytics events, security identifiers, and similar technologies to keep you signed in, remember preferences, protect accounts, prevent fraud, understand feature usage, diagnose errors, and improve the service. Some technologies are necessary for authentication and security; optional analytics or marketing tools may be adjusted when controls are available.",
      "We may process sensitive information where you provide it, where it is visible in content, where naturist-community participation implies sensitive context, or where processing is necessary for safety, verification, accessibility support, legal compliance, or member protection. Do not submit sensitive information unless you are comfortable with it being handled under these policies and the visibility setting you choose.",
    ],
    cards: [
      "Authorized agents must show permission and may still require identity verification of the affected member.",
      "We do not discriminate against members for exercising valid privacy rights, but some requests may limit features that require the information.",
      "Browser cookie controls may affect login, saved preferences, uploads, security checks, and member features.",
      "If local law requires a separate regional notice, BareUnity may provide it in-product, by email, or through this legal center.",
    ],
  },
  {
    id: "eligibility-verification",
    eyebrow: "Eligibility & Verification",
    title: "Adults only, identity honesty, and review standards",
    body: [
      "BareUnity is strictly for people who are at least 18 years old and legally allowed to access adult naturist community content where they live and where they use the service. Minors may not register, appear in nude content, use member accounts, be invited into member-only spaces, be shown in member galleries, or be discussed in a sexualized or exploitative way.",
      "We may require account review, age confirmation, identity evidence, duplicate-account checks, consent or conduct prompts, fraud signals, community-fit review, sanctions or abuse screening, manual review, or additional verification before granting, continuing, or restoring access. Verification does not guarantee that every member is safe, truthful, available, compatible, law-abiding, or endorsed by BareUnity.",
      "If we believe someone is underage, impersonating another person, using false information, evading enforcement, exploiting members, creating duplicate accounts, misusing verification, or creating safety or legal risk, we may deny registration, suspend access, remove content, preserve evidence, notify affected users, and report serious issues to appropriate authorities or service providers.",
    ],
    cards: [
      "Use your own accurate registration and verification information; do not submit altered documents, borrowed identities, AI-generated identities, or misleading profile details.",
      "Do not create accounts for others, let anyone else use your account, or help suspended members return without permission.",
      "Do not upload, request, view, discuss, joke about, or distribute sexualized or nude material involving minors under any circumstance.",
      "Approval can be revoked at any time if later information shows the account creates risk, violates policy, or no longer meets eligibility standards.",
    ],
  },
  {
    id: "community-guidelines",
    eyebrow: "Community Guidelines",
    title: "Consent-first naturist conduct rules",
    body: [
      "BareUnity exists for non-sexualized naturist community, body acceptance, friendship, travel discovery, conversation, and respectful shared experiences. Nudity in this context is treated as normal, non-exploitative, and consent-based; members must not sexualize, pressure, objectify, shame, fetishize, rate, rank, stalk, or harass others.",
      "Members must obtain clear consent before sending direct messages, making personal comments, discussing someone’s body, requesting photos, suggesting meetups, sharing contact details, tagging people, reposting content, using someone’s image, or taking any interaction outside BareUnity. Silence, prior contact, profile visibility, naturist identity, a friend request, or attendance at a naturist venue is not consent.",
      "Prohibited conduct includes harassment, stalking, threats, hate speech, sexual solicitation, non-consensual sexual content, coercion, grooming, exploitation, doxxing, blackmail, impersonation, spam, scams, illegal activity, graphic violence, encouragement of self-harm, privacy invasion, repeated boundary testing, and retaliation against people who report or decline contact.",
      "Members should communicate with patience and respect across languages, cultures, body types, disabilities, ages, genders, sexual orientations, races, religions, and naturist experience levels. Being direct about boundaries is allowed; arguing with boundaries, mocking them, or seeking loopholes is not.",
    ],
    cards: [
      "Respect 'no,' 'not now,' no response, a block, a moderator instruction, and changed boundaries immediately.",
      "Do not screenshot, record, download, copy, repost, identify, or share member content without explicit permission from every identifiable adult involved.",
      "Report safety concerns, suspicious accounts, non-consensual content, grooming, exploitation, or policy violations through available tools or by emailing jeroen@bareunity.com.",
      "Moderation decisions may consider context, patterns, severity, member vulnerability, prior warnings, off-platform spillover, and community safety rather than isolated words alone.",
    ],
  },
  {
    id: "prohibited-content",
    eyebrow: "Zero-Tolerance Content Rules",
    title: "Material and conduct that are never allowed",
    body: [
      "BareUnity has zero tolerance for child sexual abuse material, sexual exploitation of minors, trafficking, coercion, non-consensual intimate imagery, revenge content, hidden-camera content, threats to expose someone, extortion, grooming, credible violence, terroristic threats, and content that helps people commit serious harm. We may remove, preserve, report, and escalate this material without prior notice.",
      "Do not upload or request pornography, explicit sexual acts, fetishized nudity, sexual services, paid sexual contact, escorting, prostitution, sexualized ratings, body-part closeups intended to arouse, content involving intoxicated or incapacitated people, or content that turns naturism into sexual solicitation. BareUnity is for non-sexual naturist community, not sexual marketplace activity.",
      "Do not post instructions for evading law enforcement, bypassing moderation, stealing accounts, scraping content, creating fake verification materials, finding members offline without consent, or identifying people from private content. Attempts to test these boundaries may lead to immediate removal even if no harm has occurred yet.",
    ],
    cards: [
      "If you discover illegal or exploitative content, do not redistribute it; report it immediately and preserve only what is necessary for a safety report.",
      "Members who solicit, normalize, minimize, joke about, or trade exploitative content may be permanently removed and reported.",
      "BareUnity may hash, fingerprint, quarantine, or preserve dangerous media for safety, legal, and anti-abuse purposes.",
      "Content that is legal elsewhere may still be banned here if it conflicts with BareUnity’s consent-first naturist purpose.",
    ],
  },
  {
    id: "content-media-policy",
    eyebrow: "Content & Media Policy",
    title: "Photos, posts, galleries, comments, and licenses",
    body: [
      "You keep ownership of content you submit to BareUnity, but you grant BareUnity a worldwide, non-exclusive, royalty-free license to host, store, reproduce, resize, crop, transcode, display, transmit, moderate, remove, analyze for safety, create backups of, and technically process that content for operating, securing, improving, and promoting the service within the visibility settings and feature context you choose.",
      "Only upload content you have the right to share and that accurately reflects the people, location, and context shown. Every identifiable person in nude, intimate, private, or sensitive content must be an adult who gave informed consent for the content to be captured and shared on BareUnity under the selected visibility setting.",
      "Do not upload illegal content, sexual exploitation, non-consensual intimate imagery, revenge porn, voyeuristic content, hidden-camera material, content involving minors, stolen media, copyrighted material you lack rights to use, malware, deceptive deepfakes, face swaps, AI-generated impersonations, or content designed to humiliate, threaten, expose, or locate someone.",
      "BareUnity may remove, blur, restrict, downrank, quarantine, watermark, fingerprint, preserve, or report content when it appears to violate policy, law, rights, privacy, safety, or the naturist purpose of the service. Removal from active pages may not instantly remove copies from backups, caches, moderation records, shared messages, legal holds, or third-party devices.",
    ],
    cards: [
      "You are responsible for model releases, photographer rights, venue rules, permissions, copyright rights, location privacy, and consent for the content you post.",
      "Venue or event photos should respect posted rules and the privacy of everyone present, including people in backgrounds, mirrors, windows, reflections, and metadata.",
      "Content visibility controls reduce exposure but cannot guarantee that other members will not misuse what they can see.",
      "Copyright, impersonation, privacy, or consent complaints can be sent to jeroen@bareunity.com with enough detail for review.",
    ],
  },
  {
    id: "messaging-safety",
    eyebrow: "Messaging & Safety",
    title: "Private communication, reports, and enforcement",
    body: [
      "Messages are provided to help adult members communicate respectfully. Do not use messages for sexual solicitation, pressure, explicit requests, paid services, spam, scams, threats, harassment, evasion of blocks, unsolicited images, attempts to obtain private media, or attempts to move members to unsafe channels.",
      "BareUnity may use automated signals, member reports, metadata, human review, rate limits, account restrictions, trust scores, file scanning, abuse keywords, link warnings, and preservation tools to investigate abuse and protect the community. We do not promise to proactively review every message, but reported or suspicious activity may be reviewed when appropriate and lawful.",
      "Enforcement actions may include warnings, content removal, message restrictions, reduced visibility, feature limits, verification requests, device or IP blocks, temporary suspension, permanent account removal, evidence preservation, refund denial, chargeback defense, or reports to hosting providers, payment providers, venue partners, or authorities where needed.",
    ],
    cards: [
      "Block or report members who ignore boundaries, rush intimacy, request secrecy, ask for off-platform contact too quickly, or make you feel unsafe.",
      "Emergency situations should be directed to local emergency services first; BareUnity is not an emergency response provider.",
      "False, malicious, selective, edited, or retaliatory reports can themselves lead to enforcement.",
      "We may preserve records related to safety reports even if an account is deleted, restricted, or later reinstated.",
    ],
  },
  {
    id: "offline-meetups-events",
    eyebrow: "Offline Meetups & Events",
    title: "Member meetups, travel safety, and real-world boundaries",
    body: [
      "BareUnity may help members discover people, venues, map spots, stays, and activities, but members are responsible for their own decisions when meeting offline. BareUnity does not screen every person, inspect every location, supervise meetups, provide transportation, provide security, insure events, or guarantee that offline experiences will be safe, legal, comfortable, accessible, or consistent with online descriptions.",
      "When planning an offline meetup, use public or established naturist venues where possible, confirm venue rules directly, tell a trusted person where you are going, arrange your own transportation, keep control of your documents and payment methods, and leave immediately if boundaries, consent, or safety expectations change.",
      "Do not pressure members to meet, travel, share lodging, consume substances, remove clothing, be photographed, keep secrets, or ignore their own safety plan. Consent can be withdrawn at any time, including during an event, trip, photoshoot, ride, stay, or private conversation.",
    ],
    cards: [
      "BareUnity is not responsible for injuries, assaults, theft, illness, travel disruption, venue disputes, weather, cancellations, illegal conduct, or member behavior at offline meetups.",
      "Respect local laws, public nudity rules, venue membership requirements, photography bans, alcohol or substance rules, and quiet hours.",
      "Report serious offline incidents that started through BareUnity so we can assess platform safety actions.",
      "Do not use BareUnity to organize secret, coercive, unsafe, discriminatory, illegal, or non-consensual gatherings.",
    ],
  },
  {
    id: "bookings-venues",
    eyebrow: "Bookings, Venues & Third Parties",
    title: "External listings, stays, activities, and partner links",
    body: [
      "BareUnity may display naturist-friendly hotels, Airbnbs, resorts, spas, activities, map spots, community locations, events, providers, or external links for discovery and convenience. Unless a page clearly says otherwise, listings are informational and any reservation, payment, cancellation, refund, check-in rule, accessibility need, safety issue, travel document, tax, deposit, damage claim, or dispute is handled directly between you and the third-party provider.",
      "BareUnity does not own, operate, inspect, control, insure, endorse, employ, license, or guarantee third-party venues, hosts, activities, listings, availability, prices, photos, amenities, rules, safety practices, background checks, accessibility, legality, suitability, or member experiences. Information can change without notice and should be confirmed directly with the provider before travel, payment, or disclosure of personal information.",
      "Members and providers must not misrepresent listings, post fake availability, scrape member data, bypass venue rules, discriminate unlawfully, pressure guests, hide fees, manipulate reviews, or use BareUnity to arrange illegal, unsafe, sexual, exploitative, or non-consensual activity.",
    ],
    cards: [
      "Confirm age policies, naturist rules, privacy expectations, photography rules, cancellation terms, guest limits, accessibility, deposits, and local laws directly with each provider.",
      "BareUnity is not responsible for travel costs, missed reservations, venue closures, injuries, property loss, refunds, chargebacks, provider disputes, inaccurate listings, or off-platform messages.",
      "Report inaccurate, unsafe, discriminatory, fraudulent, or abusive listings so we can review visibility on BareUnity.",
      "External websites have their own terms, privacy policies, cookies, prices, cancellation rules, and support processes.",
    ],
  },
  {
    id: "payments-subscriptions",
    eyebrow: "Payments & Subscriptions",
    title: "Fees, renewals, refunds, taxes, and chargebacks",
    body: [
      "If BareUnity offers paid features, subscriptions, memberships, verification fees, promoted listings, venue tools, or other paid services, the price, billing period, included features, renewal terms, cancellation method, trial terms, and refund rules shown at checkout or in account settings will apply. Taxes, currency conversion, card fees, app-store fees, payment-provider charges, or bank fees may be added where applicable.",
      "Paid access may renew automatically if the checkout flow states that renewal applies. You are responsible for keeping payment details current and cancelling before renewal if you do not want future charges. Deleting the app, ignoring emails, deleting content, being inactive, or stopping use may not automatically cancel a paid plan handled by a payment provider or app store.",
      "BareUnity may deny refunds for used, partially used, promotional, discounted, trial, verification, administrative, safety-related, moderation-related, or listing-review fees except where required by law or expressly promised at checkout. We may suspend paid features for failed payments, chargebacks, suspected fraud, abuse, sanctions risk, payment-provider requirements, or policy violations.",
    ],
    cards: [
      "Any current paid terms presented at checkout control over older general descriptions on this page for that purchase.",
      "Contact jeroen@bareunity.com for billing questions and include the account email, transaction date, amount, payment provider, and receipt if available.",
      "Venue payments made on third-party sites are governed by that provider, not BareUnity.",
      "Fraudulent chargebacks, payment abuse, or attempts to obtain services without payment may lead to account restrictions, collection efforts, or evidence preservation.",
    ],
  },
  {
    id: "intellectual-property",
    eyebrow: "Intellectual Property",
    title: "BareUnity rights, member rights, and takedown requests",
    body: [
      "BareUnity’s name, branding, interface, designs, software, databases, compilation of content, copy, graphics, icons, layouts, code, safety tools, and service materials are owned by BareUnity or its licensors and may not be copied, scraped, framed, reverse engineered, resold, sublicensed, imitated, or used to imply endorsement without written permission.",
      "Members must respect copyrights, trademarks, publicity rights, privacy rights, contractual restrictions, venue rules, photographer rights, model releases, and confidentiality obligations. If you believe content on BareUnity infringes your rights, email jeroen@bareunity.com with your name, contact details, the content location, the rights involved, a statement explaining the issue, and enough information for us to evaluate the request.",
      "We may remove or restrict content, request more information, restore content when appropriate, terminate repeat infringers, disable links, limit search visibility, or preserve records connected to intellectual-property disputes. Knowingly false claims, abusive takedowns, or false counterclaims may create legal liability and platform enforcement.",
    ],
    cards: [
      "Do not use BareUnity logos, screenshots, member content, private community materials, or policy text in ads, press, training data, external posts, or competing products without permission.",
      "Credit alone does not make copyrighted, private, licensed, or confidential material lawful to upload.",
      "Report impersonation, stolen photos, fake profiles, deepfakes, cloned profiles, and unauthorized commercial use promptly.",
      "BareUnity may disable accounts that repeatedly violate rights or use the platform to distribute stolen, misleading, or non-consensual material.",
    ],
  },
  {
    id: "accessibility-inclusion",
    eyebrow: "Accessibility & Inclusion",
    title: "Inclusive participation and accessibility feedback",
    body: [
      "BareUnity aims to make the service welcoming to adult naturists across body types, ages, disabilities, genders, sexual orientations, races, nationalities, religions, family structures, relationship statuses, and backgrounds, while preserving safety, consent, legality, and non-sexual naturist norms.",
      "Discrimination, demeaning body commentary, accessibility shaming, fetishization, exclusionary harassment, hateful conduct, slurs, coded harassment, or attempts to exclude protected groups from community participation are not allowed. Members should communicate venue accessibility needs, privacy preferences, and support requirements directly and respectfully when planning offline activities.",
      "We welcome accessibility feedback at jeroen@bareunity.com. Please describe the page, feature, device, assistive technology, barrier, expected behavior, actual behavior, and any workaround that helped. We will consider feedback when prioritizing improvements, although specific fixes may depend on technical complexity, safety, available resources, and product priorities.",
    ],
    cards: [
      "Use respectful names, pronouns, boundaries, accessibility needs, and communication preferences shared by other members.",
      "Do not pressure anyone to disclose medical, disability, transition, trauma, relationship, immigration, religion, or personal history.",
      "Venue accessibility information may be incomplete and should be confirmed with the provider before travel.",
      "Inclusion does not protect conduct that violates consent, safety, age, anti-harassment, anti-exploitation, or legal rules.",
    ],
  },
  {
    id: "enforcement-appeals",
    eyebrow: "Moderation, Enforcement & Appeals",
    title: "How BareUnity reviews reports and applies consequences",
    body: [
      "BareUnity may moderate through member reports, automated signals, manual review, trusted reviewer input, safety keywords, image or file checks, account history, metadata, device or IP patterns, and contextual evidence. We may act before completing a full investigation when immediate safety, legal, fraud, or platform-integrity risks exist.",
      "Consequences may include no action, education, warnings, content edits, content removal, visibility limits, message limits, feature blocks, temporary suspension, permanent removal, re-verification, device or network blocks, venue-listing removal, refund denial, evidence preservation, or reports to authorities or service providers. We may also reverse or adjust actions when new information supports a different outcome.",
      "If you believe an enforcement action was a mistake, contact jeroen@bareunity.com with your account email, the action you are appealing, relevant context, and any evidence you want reviewed. Appeals do not guarantee reinstatement, delayed enforcement, restored content, refunds, or a detailed explanation where safety, privacy, legal, or abuse-prevention reasons limit what we can share.",
    ],
    cards: [
      "Do not create new accounts, contact reporters, threaten witnesses, delete evidence, or retaliate while an investigation or appeal is pending.",
      "We may consider off-platform conduct when it targets BareUnity members, uses BareUnity content, evades BareUnity enforcement, or creates community safety risk.",
      "Repeat, severe, exploitative, or bad-faith violations may result in permanent removal without warning.",
      "Moderation records may be retained after account closure to prevent repeat abuse, support appeals, comply with law, and protect members.",
    ],
  },
  {
    id: "legal-disputes",
    eyebrow: "Legal, Disputes & Liability",
    title: "Disclaimers, limitations, indemnity, and disputes",
    body: [
      "BareUnity is provided on an as-is and as-available basis. We work to maintain a safe and reliable service, but we do not guarantee uninterrupted access, error-free features, complete moderation, perfect security, successful verification, member identity, venue quality, travel outcomes, compatibility between members, content availability, business continuity, or preservation of every item of data.",
      "To the maximum extent allowed by law, BareUnity and its operators, contractors, vendors, affiliates, and team members are not liable for indirect, incidental, consequential, special, exemplary, punitive, emotional-distress, reputational, travel, venue, lost-profit, lost-data, business-interruption, personal-safety, third-party, or off-platform damages arising from use of the service. Non-waivable consumer, privacy, or safety rights remain available where law requires them.",
      "You agree to defend and indemnify BareUnity from claims, losses, liabilities, damages, costs, and expenses arising from your content, conduct, misuse of the service, violation of law, violation of rights, disputes with members or third parties, venue interactions, payment disputes, privacy violations, or breach of these policies, except where prohibited by law.",
      "Before starting a formal dispute, contact jeroen@bareunity.com and give BareUnity a reasonable opportunity to resolve the concern informally, unless urgent legal relief is needed or applicable law gives you a non-waivable right to proceed differently. We may suspend or terminate accounts when needed for safety, legal compliance, non-payment, fraud, abuse, inactivity, business reasons, or policy violations.",
    ],
    cards: [
      "Nothing in these policies creates employment, partnership, agency, fiduciary, medical, travel-agent, venue-operator, background-check, insurance, emergency-service, or public-authority duties.",
      "If any part of these policies is unenforceable, the remaining parts continue to apply to the maximum lawful extent.",
      "Terms that should survive account closure include content licenses, safety records, payment obligations, disclaimers, limitations, indemnity, dispute provisions, and audit records.",
      "Legal notices should be sent to jeroen@bareunity.com unless BareUnity publishes a more specific required notice address.",
    ],
  },
  {
    id: "law-enforcement",
    eyebrow: "Legal Requests & Law Enforcement",
    title: "Official requests, emergencies, and member notice",
    body: [
      "BareUnity may receive subpoenas, warrants, court orders, preservation requests, emergency disclosure requests, regulator correspondence, civil discovery requests, or other legal demands. We review requests for apparent validity, scope, jurisdiction, safety, and legal requirements before responding where practical.",
      "We may preserve or disclose account information when we believe disclosure is legally required, necessary to prevent imminent harm, needed to investigate exploitation or abuse, appropriate to enforce policies, necessary for fraud or security investigations, or necessary to protect BareUnity, members, third parties, or the public.",
      "Where legally permitted and safe, we may notify affected members about legal requests. We may delay or withhold notice if prohibited by law, if notice could create risk of harm, or if notice could undermine fraud prevention, abuse investigations, security, evidence preservation, or legal process.",
    ],
    cards: [
      "Emergency requests should identify the immediate risk, affected account, requested information, legal authority, requesting official, agency contact information, and deadline.",
      "Overbroad, informal, unverifiable, misdirected, or legally defective requests may be rejected, narrowed, delayed, or challenged.",
      "Preservation does not guarantee disclosure without valid legal process or an applicable emergency basis.",
      "Members should report immediate danger to local emergency services first and then notify BareUnity if the issue involves the platform.",
    ],
  },
  {
    id: "policy-updates-contact",
    eyebrow: "Policy Updates & Contact",
    title: "How policies change and how to reach us",
    body: [
      "BareUnity may update these policies to reflect new features, safety practices, laws, vendors, payment flows, verification methods, moderation tools, venue programs, accessibility improvements, or community needs. The legal center will show the latest update date, and material changes may also be announced in-product or by email when appropriate.",
      "Your continued use of BareUnity after an update means you accept the revised policies, unless a separate notice, consent, or opt-out right is required by law. If you disagree with an update, stop using the service and request account closure.",
      "For privacy, safety, moderation, copyright, accessibility, billing, venue listing, enforcement appeals, legal requests, or policy questions, contact BareUnity at jeroen@bareunity.com. Include enough detail for us to identify your account, understand the issue, verify authority where needed, and respond appropriately.",
    ],
    cards: [
      "Official legal name and domain/trading name: BareUnity.",
      "Universal policy contact: jeroen@bareunity.com.",
      "Members should keep account email addresses current so important notices, safety alerts, and billing messages can reach them.",
      "Archived versions may be retained for audit, compliance, safety, enforcement, and dispute-resolution purposes.",
    ],
  },
];

export function getPolicyById(id: string) {
  return policyGroups.find((policy) => policy.id === id);
}
